language: objective-c
osx_image: xcode10
before_install:
  - brew update
  - brew upgrade python
  - brew install cookiecutter
  - brew install git-flow
  - brew install swiftgen
  - brew install mono0926/license-plist/license-plist
  - brew upgrade carthage
script:
  - cookiecutter --no-input gh:artemnovichkov/swift-project-template
  - cd Project
  - xcodebuild clean analyze -project Project.xcodeproj -scheme 'Debug Development' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
